/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AppUsuariosIndexRouteImport } from './routes/_app/usuarios/index'
import { Route as AppTarefasIndexRouteImport } from './routes/_app/tarefas/index'
import { Route as AppScriptsIndexRouteImport } from './routes/_app/scripts/index'
import { Route as AppRelatoriosIndexRouteImport } from './routes/_app/relatorios/index'
import { Route as AppPipelineIndexRouteImport } from './routes/_app/pipeline/index'
import { Route as AppPerfilIndexRouteImport } from './routes/_app/perfil/index'
import { Route as AppOportunidadesIndexRouteImport } from './routes/_app/oportunidades/index'
import { Route as AppLeadsIndexRouteImport } from './routes/_app/leads/index'
import { Route as AppCustosIndexRouteImport } from './routes/_app/custos/index'
import { Route as AppContatosIndexRouteImport } from './routes/_app/contatos/index'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/_app/configuracoes/index'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes/index'
import { Route as AppAtividadesIndexRouteImport } from './routes/_app/atividades/index'
import { Route as AppAgendaIndexRouteImport } from './routes/_app/agenda/index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AppOportunidadesIdRouteImport } from './routes/_app/oportunidades/$id'
import { Route as AppLeadsIdRouteImport } from './routes/_app/leads/$id'
import { Route as AppClientesIdRouteImport } from './routes/_app/clientes/$id'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosIndexRoute = AppUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasIndexRoute = AppTarefasIndexRouteImport.update({
  id: '/tarefas/',
  path: '/tarefas/',
  getParentRoute: () => AppRoute,
} as any)
const AppScriptsIndexRoute = AppScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosIndexRoute = AppRelatoriosIndexRouteImport.update({
  id: '/relatorios/',
  path: '/relatorios/',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineIndexRoute = AppPipelineIndexRouteImport.update({
  id: '/pipeline/',
  path: '/pipeline/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilIndexRoute = AppPerfilIndexRouteImport.update({
  id: '/perfil/',
  path: '/perfil/',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadesIndexRoute = AppOportunidadesIndexRouteImport.update({
  id: '/oportunidades/',
  path: '/oportunidades/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustosIndexRoute = AppCustosIndexRouteImport.update({
  id: '/custos/',
  path: '/custos/',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosIndexRoute = AppContatosIndexRouteImport.update({
  id: '/contatos/',
  path: '/contatos/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/configuracoes/',
  path: '/configuracoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppAtividadesIndexRoute = AppAtividadesIndexRouteImport.update({
  id: '/atividades/',
  path: '/atividades/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaIndexRoute = AppAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOportunidadesIdRoute = AppOportunidadesIdRouteImport.update({
  id: '/oportunidades/$id',
  path: '/oportunidades/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIdRoute = AppLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/oportunidades/$id': typeof AppOportunidadesIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/agenda/': typeof AppAgendaIndexRoute
  '/atividades/': typeof AppAtividadesIndexRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/contatos/': typeof AppContatosIndexRoute
  '/custos/': typeof AppCustosIndexRoute
  '/leads/': typeof AppLeadsIndexRoute
  '/oportunidades/': typeof AppOportunidadesIndexRoute
  '/perfil/': typeof AppPerfilIndexRoute
  '/pipeline/': typeof AppPipelineIndexRoute
  '/relatorios/': typeof AppRelatoriosIndexRoute
  '/scripts/': typeof AppScriptsIndexRoute
  '/tarefas/': typeof AppTarefasIndexRoute
  '/usuarios/': typeof AppUsuariosIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/': typeof AppIndexRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/leads/$id': typeof AppLeadsIdRoute
  '/oportunidades/$id': typeof AppOportunidadesIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/atividades': typeof AppAtividadesIndexRoute
  '/clientes': typeof AppClientesIndexRoute
  '/configuracoes': typeof AppConfiguracoesIndexRoute
  '/contatos': typeof AppContatosIndexRoute
  '/custos': typeof AppCustosIndexRoute
  '/leads': typeof AppLeadsIndexRoute
  '/oportunidades': typeof AppOportunidadesIndexRoute
  '/perfil': typeof AppPerfilIndexRoute
  '/pipeline': typeof AppPipelineIndexRoute
  '/relatorios': typeof AppRelatoriosIndexRoute
  '/scripts': typeof AppScriptsIndexRoute
  '/tarefas': typeof AppTarefasIndexRoute
  '/usuarios': typeof AppUsuariosIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_app/leads/$id': typeof AppLeadsIdRoute
  '/_app/oportunidades/$id': typeof AppOportunidadesIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_app/agenda/': typeof AppAgendaIndexRoute
  '/_app/atividades/': typeof AppAtividadesIndexRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/_app/contatos/': typeof AppContatosIndexRoute
  '/_app/custos/': typeof AppCustosIndexRoute
  '/_app/leads/': typeof AppLeadsIndexRoute
  '/_app/oportunidades/': typeof AppOportunidadesIndexRoute
  '/_app/perfil/': typeof AppPerfilIndexRoute
  '/_app/pipeline/': typeof AppPipelineIndexRoute
  '/_app/relatorios/': typeof AppRelatoriosIndexRoute
  '/_app/scripts/': typeof AppScriptsIndexRoute
  '/_app/tarefas/': typeof AppTarefasIndexRoute
  '/_app/usuarios/': typeof AppUsuariosIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/email/unsubscribe'
    | '/clientes/$id'
    | '/leads/$id'
    | '/oportunidades/$id'
    | '/lovable/email/suppression'
    | '/agenda/'
    | '/atividades/'
    | '/clientes/'
    | '/configuracoes/'
    | '/contatos/'
    | '/custos/'
    | '/leads/'
    | '/oportunidades/'
    | '/perfil/'
    | '/pipeline/'
    | '/relatorios/'
    | '/scripts/'
    | '/tarefas/'
    | '/usuarios/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/email/unsubscribe'
    | '/'
    | '/clientes/$id'
    | '/leads/$id'
    | '/oportunidades/$id'
    | '/lovable/email/suppression'
    | '/agenda'
    | '/atividades'
    | '/clientes'
    | '/configuracoes'
    | '/contatos'
    | '/custos'
    | '/leads'
    | '/oportunidades'
    | '/perfil'
    | '/pipeline'
    | '/relatorios'
    | '/scripts'
    | '/tarefas'
    | '/usuarios'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/email/unsubscribe'
    | '/_app/'
    | '/_app/clientes/$id'
    | '/_app/leads/$id'
    | '/_app/oportunidades/$id'
    | '/lovable/email/suppression'
    | '/_app/agenda/'
    | '/_app/atividades/'
    | '/_app/clientes/'
    | '/_app/configuracoes/'
    | '/_app/contatos/'
    | '/_app/custos/'
    | '/_app/leads/'
    | '/_app/oportunidades/'
    | '/_app/perfil/'
    | '/_app/pipeline/'
    | '/_app/relatorios/'
    | '/_app/scripts/'
    | '/_app/tarefas/'
    | '/_app/usuarios/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios/': {
      id: '/_app/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof AppUsuariosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tarefas/': {
      id: '/_app/tarefas/'
      path: '/tarefas'
      fullPath: '/tarefas/'
      preLoaderRoute: typeof AppTarefasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scripts/': {
      id: '/_app/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof AppScriptsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios/': {
      id: '/_app/relatorios/'
      path: '/relatorios'
      fullPath: '/relatorios/'
      preLoaderRoute: typeof AppRelatoriosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline/': {
      id: '/_app/pipeline/'
      path: '/pipeline'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof AppPipelineIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil/': {
      id: '/_app/perfil/'
      path: '/perfil'
      fullPath: '/perfil/'
      preLoaderRoute: typeof AppPerfilIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oportunidades/': {
      id: '/_app/oportunidades/'
      path: '/oportunidades'
      fullPath: '/oportunidades/'
      preLoaderRoute: typeof AppOportunidadesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/': {
      id: '/_app/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/custos/': {
      id: '/_app/custos/'
      path: '/custos'
      fullPath: '/custos/'
      preLoaderRoute: typeof AppCustosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatos/': {
      id: '/_app/contatos/'
      path: '/contatos'
      fullPath: '/contatos/'
      preLoaderRoute: typeof AppContatosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes/': {
      id: '/_app/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atividades/': {
      id: '/_app/atividades/'
      path: '/atividades'
      fullPath: '/atividades/'
      preLoaderRoute: typeof AppAtividadesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda/': {
      id: '/_app/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AppAgendaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/oportunidades/$id': {
      id: '/_app/oportunidades/$id'
      path: '/oportunidades/$id'
      fullPath: '/oportunidades/$id'
      preLoaderRoute: typeof AppOportunidadesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads/$id': {
      id: '/_app/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AppLeadsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppLeadsIdRoute: typeof AppLeadsIdRoute
  AppOportunidadesIdRoute: typeof AppOportunidadesIdRoute
  AppAgendaIndexRoute: typeof AppAgendaIndexRoute
  AppAtividadesIndexRoute: typeof AppAtividadesIndexRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
  AppContatosIndexRoute: typeof AppContatosIndexRoute
  AppCustosIndexRoute: typeof AppCustosIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
  AppOportunidadesIndexRoute: typeof AppOportunidadesIndexRoute
  AppPerfilIndexRoute: typeof AppPerfilIndexRoute
  AppPipelineIndexRoute: typeof AppPipelineIndexRoute
  AppRelatoriosIndexRoute: typeof AppRelatoriosIndexRoute
  AppScriptsIndexRoute: typeof AppScriptsIndexRoute
  AppTarefasIndexRoute: typeof AppTarefasIndexRoute
  AppUsuariosIndexRoute: typeof AppUsuariosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppLeadsIdRoute: AppLeadsIdRoute,
  AppOportunidadesIdRoute: AppOportunidadesIdRoute,
  AppAgendaIndexRoute: AppAgendaIndexRoute,
  AppAtividadesIndexRoute: AppAtividadesIndexRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
  AppContatosIndexRoute: AppContatosIndexRoute,
  AppCustosIndexRoute: AppCustosIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
  AppOportunidadesIndexRoute: AppOportunidadesIndexRoute,
  AppPerfilIndexRoute: AppPerfilIndexRoute,
  AppPipelineIndexRoute: AppPipelineIndexRoute,
  AppRelatoriosIndexRoute: AppRelatoriosIndexRoute,
  AppScriptsIndexRoute: AppScriptsIndexRoute,
  AppTarefasIndexRoute: AppTarefasIndexRoute,
  AppUsuariosIndexRoute: AppUsuariosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
